# Generated by Django 4.1 on 2025-05-17 14:54

import agency.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Advice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(max_length=255)),
                ("answer", models.TextField(max_length=511)),
                (
                    "priority",
                    models.IntegerField(
                        choices=[
                            (1, "Low"),
                            (2, "Medium"),
                            (3, "High"),
                            (4, "Very High"),
                            (5, "Critical"),
                        ],
                        default=1,
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "question"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="CallRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "name",
                    models.CharField(
                        max_length=63,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Word must contain only letters.",
                                regex="^[a-zA-Zа-яА-ЯґҐєЄіІїЇ' ]+$",
                            )
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=255, null=True),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        max_length=63,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Word must contain only letters.",
                                regex="^[a-zA-Zа-яА-ЯґҐєЄіІїЇ' ]+$",
                            )
                        ],
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=13,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+380XXXXXXXXX'.",
                                regex="^\\+380\\d{9}$",
                            )
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "created"),
                            ("done", "done"),
                            ("in_progress", "in_progress"),
                            ("rejected", "rejected"),
                        ],
                        default="created",
                        max_length=64,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(max_length=255)),
                (
                    "photo",
                    models.ImageField(
                        upload_to=agency.models.event_type_photo_file_path
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Organizer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(max_length=511)),
                ("first_name", models.CharField(max_length=63)),
                ("last_name", models.CharField(max_length=63)),
                ("position", models.CharField(max_length=63)),
                (
                    "phone",
                    models.CharField(
                        max_length=13,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+380XXXXXXXXX'.",
                                regex="^\\+380\\d{9}$",
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "photo",
                    models.ImageField(
                        upload_to=agency.models.portfolio_photo_file_path
                    ),
                ),
                ("description", models.TextField(max_length=1023)),
                ("title", models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=63)),
                ("description", models.TextField(max_length=511)),
                (
                    "presentation",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=agency.models.service_presentation_pdf_file_path,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name=200)),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["is_approved"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "city",
                    models.CharField(
                        max_length=63,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Word must contain only letters.",
                                regex="^[a-zA-Zа-яА-ЯґҐєЄіІїЇ' ]+$",
                            )
                        ],
                    ),
                ),
                ("venue", models.CharField(blank=True, max_length=63, null=True)),
                (
                    "number_of_guests",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(999999),
                        ],
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("style", models.CharField(blank=True, max_length=63, null=True)),
                (
                    "phone",
                    models.CharField(
                        max_length=13,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+380XXXXXXXXX'.",
                                regex="^\\+380\\d{9}$",
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "created"),
                            ("done", "done"),
                            ("in_progress", "in_progress"),
                            ("rejected", "rejected"),
                        ],
                        default="created",
                        max_length=64,
                    ),
                ),
                (
                    "event_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="agency.eventtype",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="agency.service"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="Agency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=63)),
                ("articles", models.ManyToManyField(to="agency.article")),
                ("services", models.ManyToManyField(to="agency.service")),
            ],
            options={
                "verbose_name_plural": "Agency",
            },
        ),
    ]
